import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { createPreview } from '../plugins/prism/preview.mjs';
const playwright=await import(process.env.PRISM_PLAYWRIGHT_MODULE || 'playwright');
const {chromium}=playwright.default || playwright;
const directory=await mkdtemp(resolve(tmpdir(),'prism-widget-'));
const output=resolve('work/plugin-browser');await mkdir(output,{recursive:true});
let paidCalls=0;
const app=await createPreview({directory,fetcher:async()=>{paidCalls++;throw Error('No paid tests');}});
await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+app.server.address().port+'/#key='+app.token;
const browser=await chromium.launch({headless:true,executablePath:process.env.PRISM_BROWSER_EXECUTABLE || undefined,
  args:JSON.parse(process.env.PRISM_BROWSER_ARGS || '[]')});
try {
  for(const width of [1160,412]) {
    const context=await browser.newContext({viewport:{width,height:1100},isMobile:width===412,hasTouch:width===412});
    const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
    await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
    await page.goto(url);const frame=page.frameLocator('iframe');
    await frame.locator('#notice').filter({hasText:'Prism is ready'}).waitFor();
    assert.equal(await frame.locator('#mode option[value=live]').evaluate(option=>option.disabled),true);
    await frame.locator('#prompt').fill('Compare practical ways to turn an idea into a useful app.');
    await frame.locator('#compare').click();
    await frame.locator('#progress').filter({hasText:'4/4 answers'}).waitFor();
    const first=frame.locator('.answer').first();
    await first.locator('[data-score=accuracy]').selectOption('5');
    await first.locator('[data-score=usefulness]').selectOption('4');
    await first.locator('[data-score=clarity]').selectOption('4');
    await first.locator('[data-notes]').fill('Keep the practical steps; my subjective review.');
    await first.locator('[data-selected]').check();
    assert.equal(await first.locator('[data-score=accuracy]').inputValue(),'5');
    assert.equal(await first.locator('[data-score=usefulness]').inputValue(),'4');
    assert.equal(await first.locator('[data-score=clarity]').inputValue(),'4');
    await first.locator('[data-review-save]').click();
    await frame.locator('#notice').filter({hasText:'Review saved.'}).waitFor();
    assert.equal(await first.locator('.badge').textContent(),'4.3/5');
    await frame.locator('#blind').check();
    assert.equal(await first.locator('.quiet').first().textContent(),'Identity hidden');
    await frame.locator('#blind').uncheck();
    await frame.locator('#compile').click();
    await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.getElementById('draft').value.includes('Combined working draft'));
    await frame.locator('#draft').fill('My edited combined answer.');
    await frame.locator('#save-draft').click();
    await frame.locator('#draft-status').filter({hasText:'Saved on Prism server'}).waitFor();
    await frame.locator('#compile').click();
    await frame.locator('#history summary').click();
    await frame.locator('#revisions').selectOption({label:'Revision 2 · Editable compilation'});
    assert.equal(await frame.locator('#revision-preview').inputValue(),'My edited combined answer.');
    await frame.locator('#restore').click();
    await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.getElementById('draft').value==='My edited combined answer.');
    assert.equal(await frame.locator('#history-count').textContent(),'(3)');
    const downloadPromise=page.waitForEvent('download');await frame.locator('#export').click();
    const download=await downloadPromise, exported=JSON.parse(await readFile(await download.path(),'utf8'));
    assert.equal(exported.run.combined.text,'My edited combined answer.');assert.equal(exported.run.combinedHistory.length,3);
    const runId=exported.run.id;
    await page.reload();await frame.locator('#notice').filter({hasText:'Prism is ready'}).waitFor();
    await frame.locator('#sessions').selectOption(runId);
    await frame.locator('#comparison').waitFor({state:'visible'});
    assert.equal(await frame.locator('#draft').inputValue(),'My edited combined answer.');
    assert.equal(await frame.locator('#answers img').count(),0);
    assert.ok(await frame.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await frame.locator('#history summary').click();
    await page.evaluate(()=>{
      const iframe=document.querySelector('iframe');
      iframe.contentWindow.scrollTo(0,0);
      iframe.style.height=iframe.contentDocument.documentElement.scrollHeight+'px';
      window.scrollTo(0,0);
    });
    await page.screenshot({path:resolve(output,width+'-plugin.png'),fullPage:true});
    await frame.locator('#prompt').fill('Treat this as text: <img src=x onerror=alert(1)>');
    await frame.locator('#compare').click();
    await frame.locator('#run-prompt').filter({hasText:'Treat this as text:'}).waitFor();
    await frame.locator('#progress').filter({hasText:'4/4 answers'}).waitFor();
    assert.equal(await frame.locator('#answers img').count(),0);
    assert.ok((await frame.locator('.answer-text').first().textContent()).includes('<img src=x onerror=alert(1)>'));
    assert.deepEqual(errors,[]);
    console.log(width+'px MCP iframe: compare, manual scoring, blind mode, compile, save, restore, export and reopen passed.');
  }
  assert.equal(paidCalls,0);
} finally {await browser.close();await app.close();await rm(directory,{recursive:true,force:true});}
